name: learn-github-actions
on: [push]
jobs:
  vague-test-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo 
        uses: actions/checkout@v2
      - name: npm install, build, test
        run: |
          npm install
          npm run build --if-present
          npm test
      - name: Archive coverage
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/**
          retention-days: 14
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.9
        with:
          # Artifact name
          name: code-coverage-report

